### ISSUE TITLE
Export of table from MyDB to scidrive does not work

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/graywulf#34]
I used the default path (first_container/myfile.csv) . Also tested different formats and compression.
Details:
The URL is:  
http://preprod.scidrive.org/vospace-2.0/1/files_put/dropbox/first_container/myfile.csv.bz2

And the error is:

The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.

**Comment by dobos** [comment]
Let's try to reproduce this with the latest build.

**Comment by dobos** [comment]
Creating an export job caused a locking collision in SQL and timed out. Fixed now,.
