### ISSUE TITLE
Peeking tables in databases other than MyDB does not work correctly

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/graywulf#36]
For example, I tried GALEX:dbo.PhotoExtract. The columns header appear, but the content rows do not show.
I run a  "select top 10 * from GALEX:dbo.PhotoExtract" as a "quick execute" and the table shows with no problem. However, if I run it as a "execute", then I get the following error:

Cannot find the object "MYDB_1727612173.webuser.Results_1" because it does not exist or you do not have permissions.

**Comment by dobos** [comment]
This was a bug. SQ uses an empty database on the head node to look up the schema for performance reasons but since this database doesn't hold actual data it cannot be used for peeking into the tables. Now a randomly selected skynode is used for the peek feature.
