### ISSUE TITLE
execute query gives error message but actually completes

### ISSUE THREAD

**Issue by capnsue** [sciserver/graywulf#38]
if i "execute" this query: 
select top 14 * 
from SDSSDR12:dbo.Field 

the jobs tab says "failed:"
	sue99_16110914402908437	Query	11/9/2016 2:40:29 PM	11/9/2016 2:40:18 PM	11/9/2016 2:40:20 PM	failed	

and the error says:
Cannot find the object "MYDB_1544479622.webuser.Results_4" because it does not exist or you do not have permissions.

but if i go to my mydb I see a table "Results_3" with 14 rows from the field table.

	MYDB:webuser.Results_3	14	72 kB	0 B	

so it looks like it's just looking for the wrong table name?

**Comment by dobos** [comment]
This error was due to a bug in the logic for automatic naming of result tables.
