### ISSUE TITLE
SkyQuery: Export to SciDrive

### ISSUE THREAD

**Issue by mikear69** [sciserver/graywulf#39]
I picked a table in MyDB. and selected Export to SciDrive.

It failed in SkyQuery with the error below BUT a file was written in SciDrive with column headers but no data. (failed for txt, csv, xhtml, votable, BUT  worked for FITS)

Error details
	
The following message might contain useful information on why the job failed.

Error message:	The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
If you think this error is due to a bug in the system, please send an inquiry to the system administrator.

**Comment by dobos** [comment]
The problem originated from an incorrect version of .Net framework used to run the remote IO service. It's been fixed on SDSS3R but will need updates to production mydb servers before going to production.
