### ISSUE TITLE
API documentation links return an error page

### ISSUE THREAD

**Issue by raddick** [sciserver/graywulf#42]
Go to 

http://test.voservices.net/skyquery/Api/Default.aspx

Click any of the links to {Data/Jobs/Schema/Test}

Returns an error, screenshot below.

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/20152595/dcfd30fc-a68c-11e6-86a3-baf3a77379e8.png)

**Comment by dobos** [comment]
It was a config issue affecting the prod/pre-prod servers only. Fixed.
