### ISSUE TITLE
Importing a file not working correctly.

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/graywulf#43]
When I try to upload the file MyUpload.txt containing:

1,1,2
2,3,4
4,3,2

and choose the automatic file detection, what happens is that the resulting table appears  with a datetime column:

ID bigint	    1,1,2 datetime2
1	2/3/2004 12:00:00 AM
2	4/3/2002 12:00:00 AM

It works if  choose the file format as csv.

**Comment by dobos** [comment]
This is a feature. If the data type is not specified, it defaults to txt for which the column separator is space or tab. Column types are detected automatically by trying to parse them into various complex types such as datetime or guid. We could change the default from txt to csv.
