### ISSUE TITLE
query time out due to bad config (acc to Laszlo)

### ISSUE THREAD

**Issue by glemson** [sciserver/graywulf#47]
SELECT htm.htmidstart, htm.htmidend
FROM (SELECT TOP 10 ra, dec FROM SDSSDR7:PhotoObj) p
CROSS APPLY htm.CoverCircleEq(p.ra, p.dec, 10) htm

times out as quick execute

**Comment by dobos** [comment]
There was no database defined to look up the schema of UDTs from. Fixed in last deployment.
