### ISSUE TITLE
peek and query fails on DR12 detectionIndex

### ISSUE THREAD

**Issue by capnsue** [sciserver/graywulf#50]
in SDSSDR12, if you select "detectionIndex" in schema browser, peek fails with the error Invalid object name 'SkyNode_SDSSDR12.dbo.detectionIndex'.

also if you run the query 
select top 10 * from SDSSDR12:dbo.detectionIndex

it fails with An exception occured: Invalid object name 'SkyNode_SDSSDR12.dbo.detectionIndex'.

**Comment by dobos** [comment]
detection index is not available in the SkyQuery version of DR12.
