### ISSUE TITLE
Add button on query page to load sample queries

### ISSUE THREAD

**Issue by raddick** [sciserver/graywulf#55]
When the user clicks on Query (which will often be the first thing they do after logging in), they may not know what to do in the blank query window. Let's add a Samples button or similar control (like the one we have on the CasJobs query page) to load a sample query. I guess this is the inverse of the "Try this query" feature in the docs.

For comparison, look at the CasJobs query page - the "Samples" button is between the "Context" dropdown and the blank query window:

http://skyserver.sdss.org/CasJobs/SubmitJob.aspx

**Comment by dobos** [comment]
This won't be implemented, but rather users will be able to try sample queries directly from the documentation by clicking on a button.

**Comment by raddick** [comment]
We decided that there won't be a need for this after the cross-match form is ready. So we'll put our energy into that form instead.
